default_environment: dev
project_id: 019e69a9-c1f4-7ee7-bf6b-e2c60444debc
environments:
- name: dev
- name: staging
- name: prod
python: python3.11
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: meltanolabs-tap-postgres
    config:
      database: postgres
      filter_schemas:
      - public
      host: aws-1-ap-southeast-2.pooler.supabase.com
      port: 5432
      user: postgres.pwxnykvkqctmeailodbh
    select:
    - public-resale_flat_prices_from_jan_2017.*
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git setuptools<80
    config:
      batch_size: 104857600
      credentials_path: /home/dsai/5m-data-2.6-data-pipelines-orchestration/meltano-ingestion/green-bedrock-469701-s1-f70c6da65812.json
      dataset: resale
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
      method: batch_job
      project: green-bedrock-469701-s1
